[package]
name = "sbot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
serenity = "0.10.10"
tokio = {version = "1.16.1", features=["macros", "rt-multi-thread"]}

[profile.release]
opt-level = 3
debug = false
lto = true
codegen-units = 1